курсач/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

курсач/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path("admin/", admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    # path(_('payment/'), include('payment.urls', namespace='payment')),
    # path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    # path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

курсач/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

курсач/shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])

class Product(models.Model):

    category = models.ForeignKey(Category, related_name='products', blank=True,default=None,null=True, on_delete=models.SET_DEFAULT )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail',
                           args=[self.id, self.slug])

курсач/shop/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product


# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

def product_detail(request, id, slug):
    language = request.LANGUAGE_CODE
    product = get_object_or_404(Product,
                                id=id,
                                available=True)
    # TODO: Cart
    cart_product_form = CartAddProductForm()

    # TODO: Recs ar not working
    # r = Recommender()
    # recommended_products = r.suggest_products_for([product], 4)
    recommended_products = []

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                  'cart_product_form': cart_product_form,
                  'recommended_products': recommended_products})

курсач/shop/templates/shop/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}{% trans "RMDeal" %}{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="{{ STATIC_URL}}/static/logo/img.jpg">
</head>
<body>
  <div id="header">
	  	<div class = "cards">
		  	<div clss = "card front"></div>
			<img  class="logo" src="{{ STATIC_URL}}/static/logo/img.jpg" style="width: 50px; height: 50px;"></a>
			<div clss = "card back"></div>
	</div>
    <a href="/" class="logo">{% trans "ZooPets" %}</a>
    </div>
  </div>
  <div id="subheader">
    <div class="cart">
      {% with total_items=cart|length %}
          {% if cart|length > 0 %}
            {% trans "Корзина" %}
            <a href="{% url "cart:cart_detail" %}">
              {% blocktrans with total_items_plural=total_items|pluralize  total_price=cart.get_total_price %}
                {{ total_items }} item{{ total_items_plural }},
                &#8381;{{ total_price }}
              {% endblocktrans %}
            </a>
          {% else %}
            {% trans "Корзина пуста" %}
          {% endif %}
        {% endwith %}
    </div>
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>